Revert "modify grep and for, management of creating identical issues"
This reverts commit 30a95cfa

diff --git a/.github/workflows/broken-links-check.yml b/.github/workflows/broken-links-check.yml
--- a/.github/workflows/broken-links-check.yml
+++ b/.github/workflows/broken-links-check.yml
@@ -4,72 +4,60 @@ on:
     branches:
       - main
   schedule:
-    - cron: '0 0 1 * *'
+     - cron: '0 0 1 * *'
 env:
   ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
-
+ 
   contents: read
-  issues: write
-
+  issues: write 
+  
 jobs:
   check:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-      - name: Get links from README.md
-        id: get-links
-        run: |
-          LINKS=$(sed -nE 's/\[.*\]\((http[s]?:\/\/[^)]*)\)/\1/p' README.md | paste -sd ,)
-          echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
-      - name: Run Broken Links Checker
-        run: |
-          # Split the list of links into an array separated by commas
-          read -ra LINKS <<< $WEBSITE_URL
-          BROKEN_LINKS=()
-          
-          # Scan the links and verify if they are reachable
-          for link in "${LINKS[@]}"; do
-              if ! curl -IsSk "$link" > /dev/null; then
-                BROKEN_LINKS+=("$link")
-              fi
-          done
-          
-          if [ ${#BROKEN_LINKS[@]} -gt 0 ]; then
-           echo "Broken links found: ${BROKEN_LINKS[@]}" >&2
-           echo "Broken links found, failing the workflow" >&2
+    - uses: actions/checkout@v3
+    - name: Get links from README.md
+      id: get-links
+      run: |
+       LINKS=$(grep -oP '\[.*?\]\((http[s]?://[^)]*)\)' README.md | sed -E 's/\[.*\]\(([^)]+)\)/\1/' | paste -sd "," -)
+       echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
       
-           exit 1
-          else
-           echo "No broken links found"
+    - name: Run Broken Links Checker
+      run: |
+        # Dividi la lista di link in un array separato da virgola
+        IFS=',' read -ra LINKS <<< "$WEBSITE_URL"
+        BROKEN_LINKS=""
+
+        # Scansiona i link e verifica se sono raggiungibili
+        for link in "${LINKS[@]}"; do
+          if [[ $link =~ ^(http|https):// ]]; then
+            # Se il link inizia con "http://" o "https://", verifica se è raggiungibile
+            if ! curl -IsSk "$link" > /dev/null; then
+              BROKEN_LINKS="$BROKEN_LINKS,$link"
+            fi
           fi
-         
+        done
 
-      - name: Set BROKEN_LINKS as Environment Variable
-        if: failure()
-        run: |
-          # Crea un file temporaneo per memorizzare i link rotti
-          echo "${BROKEN_LINKS[@]}" > broken_links.txt
+          # Rimuovi la virgola iniziale se ci sono link non raggiungibili
+        if [ -n "$BROKEN_LINKS" ]; then
+          BROKEN_LINKS=$(echo "$BROKEN_LINKS" | cut -c 2-)
+          echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
+          echo "Broken links found: $BROKEN_LINKS"
+          echo "Broken links found, failing the workflow"
+          exit 1
+        else
+          echo "No broken links found"
+        fi
 
-      - name: Create Issue for Broken Links
-        if: failure()
-        run: |
-          # Leggi i link rotti dal file temporaneo
-          BROKEN_LINKS=$(cat broken_links.txt)
+  
 
-          # Crea una stringa con i link rotti formattati come elenco puntato
-          formatted_links=$(printf "\\n- %s" "$BROKEN_LINKS")
+    - uses: actions/checkout@v3
+      if: failure()
 
-          # Crea una stringa JSON con il corpo dell'issue
-          json_data="{\"title\":\"Broken Links Found\",\"body\":\"Broken links found:$formatted_links\"}"
-
-          # Invia una richiesta POST per creare un problema su GitHub
-          curl -X POST \
-            -H "Accept: application/vnd.github.v3+json" \
-            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            -d "$json_data" \
-            https://api.github.com/repos/${{ github.repository }}/issues
-      
-      
-      
-      
+    - uses: JasonEtco/create-an-issue@v2
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        filename: ${{ env.ISSUE_TEMPLATE }}
+      if: failure()
