modify grep and for, management of creating identical issues

diff --git a/.github/workflows/broken-links-check.yml b/.github/workflows/broken-links-check.yml
--- a/.github/workflows/broken-links-check.yml
+++ b/.github/workflows/broken-links-check.yml
@@ -2,62 +2,72 @@ name: Broken Links Checker
 on:
   push:
     branches:
-      - main
+      - master
   schedule:
-     - cron: '0 0 1 * *'
+    - cron: '0 0 1 * *'
 env:
   ISSUE_TEMPLATE: ".github/workflows/ISSUE_TEMPLATE.md"
- 
+
   contents: read
-  issues: write 
-  
+  issues: write
+
 jobs:
   check:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Get links from README.md
-      id: get-links
-      run: |
-       LINKS=$(grep -oP '\[.*?\]\((http[s]?://[^)]*)\)' README.md | sed -E 's/\[.*\]\(([^)]+)\)/\1/' | paste -sd "," -)
-       echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
-      
-    - name: Run Broken Links Checker
-      run: |
-        # Dividi la lista di link in un array separato da virgola
-        IFS=',' read -ra LINKS <<< "$WEBSITE_URL"
-        BROKEN_LINKS=""
+      - uses: actions/checkout@v3
+      - name: Get links from README.md
+        id: get-links
+        run: |
+          LINKS=$(sed -nE 's/\[.*\]\((http[s]?:\/\/[^)]*)\)/\1/p' README.md | paste -sd ,)
+          echo "WEBSITE_URL=$LINKS" >> $GITHUB_ENV
 
-        # Scansiona i link e verifica se sono raggiungibili
-        for link in "${LINKS[@]}"; do
-          if [[ $link =~ ^(http|https):// ]]; then
-            # Se il link inizia con "http://" o "https://", verifica se è raggiungibile
-            if ! curl -IsSk "$link" > /dev/null; then
-              BROKEN_LINKS="$BROKEN_LINKS,$link"
+      - name: Run Broken Links Checker
+        run: |
+          # Split the list of links into an array separated by commas
+          IFS=',' read -ra LINKS <<< "$WEBSITE_URL"
+          BROKEN_LINKS=()
+          
+          # Scan the links and verify if they are reachable
+          for link in "${LINKS[@]}"; do
+              if ! curl -IsSk "$link" > /dev/null; then
+                BROKEN_LINKS+=("$link")
+              fi
             fi
+          done
+          
+          if [ ${#BROKEN_LINKS[@]} -gt 0 ]; then
+           echo "Broken links found: ${BROKEN_LINKS[@]}" >&2
+           echo "Broken links found, failing the workflow" >&2
+           exit 1
+          else
+           echo "No broken links found"
           fi
-        done
 
-          # Rimuovi la virgola iniziale se ci sono link non raggiungibili
-        if [ -n "$BROKEN_LINKS" ]; then
-          BROKEN_LINKS=$(echo "$BROKEN_LINKS" | cut -c 2-)
-          echo "BROKEN_LINKS=$BROKEN_LINKS" >> $GITHUB_ENV
-          echo "Broken links found: $BROKEN_LINKS"
-          echo "Broken links found, failing the workflow"
-          exit 1
-        else
-          echo "No broken links found"
-        fi
+      - name: Read issue template file
+        id: read-template
+        run: |
+          ISSUE_TEMPLATE=$(cat ${{ env.ISSUE_TEMPLATE_PATH }})
+          echo "ISSUE_TEMPLATE=$ISSUE_TEMPLATE" >> $GITHUB_ENV
 
-  
-
-    - uses: actions/checkout@v3
-      if: failure()
-
-    - uses: JasonEtco/create-an-issue@v2
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        filename: ${{ env.ISSUE_TEMPLATE }}
-      if: failure()
+      - name: Create or Update an issue for broken links
+        run: |
+          ISSUE_BODY=$(echo "$ISSUE_TEMPLATE" | sed 's/{{BROKEN_LINKS}}/'"$BROKEN_LINKS"'/g')
+          ISSUE_TITLE="Broken Links Found"
+          ISSUE_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+           "https://api.github.com/repos/${{ github.repository }}/issues?state=open" | \
+            jq -r --arg TITLE "$ISSUE_TITLE" '.[] | select(.title == $TITLE) | .number')
+                
+          if [ -z "$ISSUE_NUMBER" ]; then
+            echo "Creating a new issue..."
+            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -d '{"title":"'"$ISSUE_TITLE"'","body":"'"$ISSUE_BODY"'"}' \
+              "https://api.github.com/repos/${{ github.repository }}/issues"
+          else
+            echo "Updating existing issue #$ISSUE_NUMBER..."
+            curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+               -d '{"body":"'"$ISSUE_BODY"'"}' \
+               "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"
+          fi
+        if: failure()
